# Generated by Django 3.2.4 on 2021-09-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user2',
        ),
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(db_column='userId', related_name='conversations', to='messenger_backend.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='readby',
            field=models.ManyToManyField(db_column='userId', related_name='readMessages', to='messenger_backend.User'),
        ),
    ]
