# Generated by Django 3.2.4 on 2021-09-15 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user1ViewedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2ViewedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
