# Generated by Django 3.2.4 on 2021-09-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0004_auto_20210916_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user1ViewedAt',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user2ViewedAt',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
